import type { ClosetItem } from './supabase';

// Fallback inventory used when Supabase isn't configured yet — lets the
// coordination engine be demoed before the database/storage bucket exists.
export const MOCK_CLOSET: ClosetItem[] = [
  {
    id: 'top-oxford-white',
    name: 'White Oxford Shirt',
    category: 'top',
    formality: 8,
    warmth: 3,
    color: '#F5F5F0',
    model_url: '/models/oxford-white.glb',
    in_laundry: false,
  },
  {
    id: 'top-tee-navy',
    name: 'Navy T-Shirt',
    category: 'top',
    formality: 2,
    warmth: 2,
    color: '#1F3A5F',
    model_url: '/models/tee-navy.glb',
    in_laundry: false,
  },
  {
    id: 'bottom-chinos-tan',
    name: 'Tan Chinos',
    category: 'bottom',
    formality: 6,
    warmth: 4,
    color: '#C9A876',
    model_url: '/models/chinos-tan.glb',
    in_laundry: false,
  },
  {
    id: 'bottom-jeans-blue',
    name: 'Blue Jeans',
    category: 'bottom',
    formality: 3,
    warmth: 4,
    color: '#3B5998',
    model_url: '/models/jeans-blue.glb',
    in_laundry: true,
  },
  {
    id: 'outerwear-blazer-navy',
    name: 'Navy Blazer',
    category: 'outerwear',
    formality: 9,
    warmth: 5,
    color: '#1B2A4A',
    model_url: '/models/blazer-navy.glb',
    in_laundry: false,
  },
  {
    id: 'outerwear-parka-black',
    name: 'Black Winter Parka',
    category: 'outerwear',
    formality: 2,
    warmth: 9,
    color: '#111111',
    model_url: '/models/parka-black.glb',
    in_laundry: false,
  },
  {
    id: 'footwear-oxford-brown',
    name: 'Brown Oxfords',
    category: 'footwear',
    formality: 8,
    warmth: 3,
    color: '#5B3A29',
    model_url: '/models/oxford-brown.glb',
    in_laundry: false,
  },
  {
    id: 'footwear-sneakers-white',
    name: 'White Sneakers',
    category: 'footwear',
    formality: 2,
    warmth: 2,
    color: '#FFFFFF',
    model_url: '/models/sneakers-white.glb',
    in_laundry: false,
  },
];
